package iedcr.shakawat.sariapplication.models

class Info {
    companion object{
        var hos_id = ""
        var id = 0
        var pt_id = ""
        var ward_no=""
        var bed_no=""
        var scd=""
        var da=""
        var dept = 0
        var name = ""
        var gen = 0
        var age = ""
        var vil = ""
        var un = ""
        var upz = ""
        var dis = ""
        var mob = ""
        var is_hck = 0
        var is_cpw = 0
        var is_bpr = 0
        var is_lbmw = 0
        var has_th = 0
        var th_place = ""
        var asthma = 0
        var diabetes = 0
        var crd = 0
        var ccd = 0
        var cld = 0
        var crnd = 0
        var cnd = 0
        var chd = 0
        var preg = 0
        var cancer = 0
        var oth_med_his = ""
        var onset_ill = ""
        var sore_throat=0
        var run_nose=0
        var diff_breath=0
        var headache=0
        var bodyache=0
        var diarrhoea=0
        var symp_oth=0
        var symp_oth_txt=""
        var convul=0
        var lathergy=0
        var udrink=0
        var vomit=0
        var stridor=0
        var chest=0
        var pulse=""
        var temp=""
        var sys=""
        var dbp=""
        var rr=0
        var cyn=0
        var rhonchi=0
        var crep=0
        var xray=0
        var xray_txt=""
        var ts=0
        var ns=0
        var nasao=0
        var sputum=0
        var spec_oth=0
        var spec_oth_txt=""

        fun clear() {
            id = 0
            pt_id = ""
            ward_no=""
            bed_no=""
            scd = ""
            da=""
            dept = 0
            name = ""
            gen = 0
            age = ""
            vil = ""
            un = ""
            upz = ""
            dis = ""
            mob = ""
            is_hck = 0
            is_cpw = 0
            is_bpr = 0
            is_lbmw = 0
            has_th = 0
            th_place = ""
            asthma = 0
            diabetes = 0
            crd = 0
            ccd = 0
            cld = 0
            crnd = 0
            cnd = 0
            chd = 0
            preg = 0
            cancer = 0
            oth_med_his = ""
            onset_ill = ""
            sore_throat=0
            run_nose=0
            diff_breath=0
            headache=0
            bodyache=0
            diarrhoea=0
            symp_oth=0
            symp_oth_txt=""
            convul=0
            lathergy=0
            udrink=0
            vomit=0
            stridor=0
            chest=0
            pulse=""
            temp=""
            sys=""
            dbp=""
            rr=0
            cyn=0
            rhonchi=0
            crep=0
            xray=0
            xray_txt=""
            ts=0
            ns=0
            nasao=0
            sputum=0
            spec_oth=0
            spec_oth_txt=""
        }
    }
}