package iedcr.shakawat.sariapplication.models

class List {
    var hos_id = ""
    var id = 0
    var pt_id = ""
    var ward_no=""
    var bed_no=""
    var scd=""
    var da=""
    var dept = 0
    var name = ""
    var gen = 0
    var age = ""
    var vil = ""
    var un = ""
    var upz = ""
    var dis = ""
    var mob = ""
    var is_hck = 0
    var is_cpw = 0
    var is_bpr = 0
    var is_lbmw = 0
    var has_th = 0
    var th_place = ""
    var asthma = 0
    var diabetes = 0
    var crd = 0
    var ccd = 0
    var cld = 0
    var crnd = 0
    var cnd = 0
    var chd = 0
    var preg = 0
    var cancer = 0
    var oth_med_his = ""
    var onset_ill = ""
    var sore_throat=0
    var run_nose=0
    var diff_breath=0
    var headache=0
    var bodyache=0
    var diarrhoea=0
    var symp_oth=0
    var symp_oth_txt=""
    var convul=0
    var lathergy=0
    var udrink=0
    var vomit=0
    var stridor=0
    var chest=0
    var pulse=""
    var temp=""
    var sys=""
    var dbp=""
    var rr=0
    var cyn=0
    var rhonchi=0
    var crep=0
    var xray=0
    var xray_txt=""
    var ts=0
    var ns=0
    var nasao=0
    var sputum=0
    var spec_oth=0
    var spec_oth_txt=""
}